### ISSUE TITLE
Navigate to next question without using next button

### ISSUE THREAD

**Issue by Kazumna** [QuickBirdEng/survey_kit#118]
Does anyone know how to remove next button? Just wanna go to next page by tapping on the question. Is that possible?

**Comment by Numoy** [comment]
Currently, the only way would be to override the 'StepView' and implement complete custom steps. But this would be a lot of work since you cannot use (our) pre-build steps.

You can checkout the develop branch, we made a lot of changes there which makes it super easy to change the next button. Just be aware this is still in development state, but we are planning to release the new version in a couple of months.

**Comment by Kazumna** [comment]
Thanks for your kind reply and looking forward to your next release.
