### ISSUE TITLE
Conditional Statement for Navigation Rule

### ISSUE THREAD

**Issue by ayiepp** [QuickBirdEng/survey_kit#77]
Hi, sorry for my bad english, i want to know if it is possible to create navigation rule from 2 step identifier. i use single choice question in every questionstep, and i want it to navigate if the 2 question result equals to 'yes'.

![Screenshot 2022-08-10 062526](https://user-images.githubusercontent.com/87024864/183772589-44d5a12e-d1eb-4aa3-a84b-e30b93ac9e17.png)

**Comment by Numoy** [comment]
I'm not 100% sure what your question is.

In this example, you navigate from task.steps[2] (which is actually step 3 since Dart indexing is based on 0) to task.step[3] when the answers is "Yes" and navigate to task.steps[4] when the answer is "No".

 If you want to customize the "input" you have to change the "valueIdentifier" of the step.

**Comment by Numoy** [comment]
Since you did not answer I guess you solved it yourself. If the question is still open please open another issue!
